# Generated by Django 4.2.16 on 2026-05-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='annual_leave_days',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='company',
            name='date_format',
            field=models.CharField(default='YYYY-MM-DD', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='grace_period_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_employees',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='company',
            name='overtime_threshold_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='sick_leave_days',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(default='basic', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='working_days_per_week',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='company',
            name='working_hours_per_day',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
    ]
