# Generated by Django 4.2.8 on 2026-05-11 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("employees", "0002_branch_employee_branch"),
        ("core", "0002_update_company_model"),
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeSalaryStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "custom_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override the default rule amount for this employee",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
        migrations.AlterModelOptions(
            name="salaryrule",
            options={"ordering": ["rule_type", "name"]},
        ),
        migrations.AddField(
            model_name="payrollrecord",
            name="absent_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payrollrecord",
            name="breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="payrollrecord",
            name="leave_days",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="payrollrecord",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payrollrecord",
            name="present_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payrollrecord",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_payrolls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollrecord",
            name="working_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salaryrule",
            name="applies_to_all",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="salaryrule",
            name="specific_employees",
            field=models.ManyToManyField(
                blank=True, related_name="salary_rules", to="employees.employee"
            ),
        ),
        migrations.AlterField(
            model_name="payrollrecord",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payroll_records",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="salaryrule",
            name="calculation_method",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Amount"),
                    ("percentage", "Percentage of Basic Salary"),
                    ("formula", "Custom Formula"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrecord",
            index=models.Index(
                fields=["company", "period_start", "period_end"],
                name="payroll_pay_company_8ca75b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrecord",
            index=models.Index(
                fields=["employee", "period_start"],
                name="payroll_pay_employe_60b392_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrecord",
            index=models.Index(
                fields=["is_processed"], name="payroll_pay_is_proc_e32d5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salaryrule",
            index=models.Index(
                fields=["company", "is_active"], name="payroll_sal_company_0607ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salaryrule",
            index=models.Index(
                fields=["rule_type"], name="payroll_sal_rule_ty_a00e28_idx"
            ),
        ),
        migrations.AddField(
            model_name="employeesalarystructure",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.company"
            ),
        ),
        migrations.AddField(
            model_name="employeesalarystructure",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_structure",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeesalarystructure",
            name="salary_rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payroll.salaryrule"
            ),
        ),
        migrations.AddIndex(
            model_name="employeesalarystructure",
            index=models.Index(
                fields=["employee", "is_active"], name="payroll_emp_employe_46603e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeesalarystructure",
            index=models.Index(
                fields=["effective_from", "effective_to"],
                name="payroll_emp_effecti_2746e3_idx",
            ),
        ),
    ]
