# Generated by Django 4.2.8 on 2026-05-11 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0002_update_company_model"),
        ("authentication", "0002_role_is_system_role_permission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("password_change", "Password Change"),
                            ("role_assign", "Role Assignment"),
                            ("permission_change", "Permission Change"),
                            ("access", "Access"),
                            ("export", "Export"),
                            ("import", "Import"),
                        ],
                        max_length=50,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=255)),
                ("module", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="authenticat_user_id_3b88ca_idx",
                    ),
                    models.Index(
                        fields=["company", "timestamp"],
                        name="authenticat_company_83dc7f_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="authenticat_action_4a725a_idx",
                    ),
                    models.Index(
                        fields=["module", "timestamp"],
                        name="authenticat_module_6e41a3_idx",
                    ),
                ],
            },
        ),
    ]
