# Generated by Django 4.2.8 on 2026-05-11 11:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_update_company_model"),
        ("employees", "0002_branch_employee_branch"),
        ("leave_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.IntegerField()),
                (
                    "accrued_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "used_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "pending_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "ordering": ["-year", "leave_type__name"],
            },
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="allow_negative_balance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="requires_approval",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="days_requested",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "status"], name="leave_manag_employe_76bff2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date", "end_date"], name="leave_manag_start_d_903b4d_idx"
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.company"
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_balances",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="leave_management.leavetype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leavebalance",
            unique_together={("employee", "leave_type", "year", "company")},
        ),
    ]
